swagger: "2.0"
info:
  description: "Ce serveur a été construit dans le cadre du deuxième projet de l'AMT 2019. Ceci regroupe les APIs du premier backend du projet."
  version: "1.0.0"
  title: "AMT 2019 - Project Two API - Premier backend"
  termsOfService: ""
host: "localhost:8080"
basePath: "/"
tags:
  - name: "user"
    description: "Les opérations sur les utilisateurs"
  - name: "auth"
    description: "Les opérations pour l'authentification des utilisateur"
schemes:
  - "http"
paths:
  /users:
    post:
      tags:
        - "user"
      summary: "Créer un utilisateur"
      description: "Crée un nouvel utilisateur"
      operationId: "create"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Utilisateur à créer"
          required: true
          schema:
            $ref: "#/definitions/UserDTO"
      responses:
        201:
          description: "Opération réussie"
          schema:
            $ref: "#/definitions/UserDTO"
        403:
          description: "Accès refusé"
          schema:
            type: "string"
    get:
      tags:
        - "user"
      summary: "Liste de tous les utilisateurs"
      description: "Liste complète de tous les utilisateurs"
      operationId: "getAll"
      produces:
        - "application/json"
      parameters:
        - name: "page"
          in: "query"
          required: false
          type: "integer"
          default: 0
        - name: "pageSize"
          in: "query"
          required: false
          type: "integer"
          default: 10
      responses:
        default:
          description: "Tous les utilisateurs"
          schema:
            $ref: "#/definitions/PagedResponse"
  /users/{email}:
    get:
      tags:
        - "user"
      summary: "Récupère un utilisateur avec l'email correspondant"
      description: "Récupère un utilisateur avec l'`email` correspondant"
      operationId: "get"
      produces:
        - "application/json"
      parameters:
        - name: "email"
          in: "path"
          description: "Email de l'utilisateur à récupérer"
          required: true
          type: "string"
      responses:
        200:
          description: "Opération réussie"
          schema:
            $ref: "#/definitions/UserDTO"
        400:
          description: "Email invalide"
          schema:
            type: "string"
        404:
          description: "Utilisateur non trouvée"
          schema:
            type: "string"
    put:
      tags:
        - "user"
      summary: "Mettre à jour un utilisateur"
      description: "Mets à jour l'utilisateur avec l'`email` correspondant. Ne peut qu'être fait par un utilisateur connecté"
      operationId: "update"
      produces:
        - "application/json"
      parameters:
        - name: "email"
          in: "path"
          description: "email de l'utilisateur à mettre à jour"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Utilisateur à mettre à jour"
          required: true
          schema:
            $ref: "#/definitions/UserDTO"
      responses:
        200:
          description: "Utilisateur modifié"
          schema:
            $ref: "#/definitions/UserDTO"
        400:
          description: "Email invalide"
          schema:
            type: "string"
        403:
          description: "Accès refusé"
          schema:
            type: "string"
        404:
          description: "Utilisateur non retrouvé"
          schema:
            type: "string"
    delete:
      tags:
        - "user"
      summary: "Supprime un utilisateur"
      description: "Supprime un utilisateur avec `email` comme adresse email. Cette action ne peut qu'être effectué par l'administrateur"
      operationId: "delete"
      produces:
        - "application/json"
      parameters:
        - name: "email"
          in: "path"
          description: "Email de l'utilisateur à supprimer"
          required: true
          type: "string"
      responses:
        200:
          description: "Utilisateur supprimé"
          schema:
            type: "string"
        400:
          description: "Email invalide"
          schema:
            type: "string"
        403:
          description: "Accès refusé"
          schema:
            type: "string"
        404:
          description: "Utilisateur non trouvée"
          schema:
            type: "string"
  /users/block/{email}:
    put:
      tags:
        - "user"
      summary: "Bloque l'utilisateur ayant l'email correspondant"
      description: "Bloque l'utilisateur ayant l'`email` correspondant"
      operationId: "block"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "email"
          type: "string"
          required: true
      responses:
        200:
          description: "Utilisateur bloqué"
          schema:
            type: "string"
        404:
          description: "Utilisateur introuvable"
          schema:
            type: "string"
    delete:
      tags:
        - "user"
      summary: "Débloque l'utilisateur ayant l'email correspondant"
      description: "Débloque l'utilisateur ayant l'email correspondant"
      operationId: "unblock"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "email"
          type: "string"
          required: true
      responses:
        200:
          description: "Utilisateur débloqué"
          schema:
            type: "string"

  /users/password:
    put:
      tags:
        - "user"
      summary: "Change le mot de passe de l'utilisateur"
      description: "Change le mot de passe de l'utilisateur"
      operationId: "changePassword"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "changePassword"
          required: true
          schema:
            $ref: "#/definitions/ChangePassword"
      responses:
        200:
          description: "Opération réussie"
          schema:
            type: "string"
        400:
          description: "Données envoyés invalides"
          schema:
            type: "string"
    post:
      tags:
        - "user"
      summary: "Attribut un nouveau mot de passe à l'utilisateur"
      description: "Attribut un nouveau mot de passe suite à une réinitialisation"
      operationId: "resetPassword"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "resetPassword"
          required: true
          schema:
            $ref: "#/definitions/ResetPassword"
      responses:
        200:
          description: "Mot de passe changé"
          schema:
            type: "string"
  /users/reset-password:
    post:
      tags:
        - "user"
      summary: "Envoi le mail pour la réinitialisation du mot de passe"
      description: "Envoi le mail de réinitialisation"
      operationId: "forgotPassword"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "userId"
          required: true
          schema:
            $ref: "#/definitions/UserId"
      responses:
        200:
          description: "Mail de réinitialisation envoyé"
          schema:
            type: "string"
    get:
      tags:
        - "user"
      summary: "Ouvre la page pour le changement de mot de passe"
      description: "Ouvre la page pour le changement du mot de passe"
      operationId: "resetPasswordPage"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "token"
          required: true
          type: "string"
      responses:
        200:
          description: "Page pour réinitialisation du mot de passe"
          schema:
            type: "string"
  /users/code:
    get:
      tags:
        - "user"
      summary: "Envoi un code vers à l'adresse mail renseigné"
      description: "Envoi un code vers l'adresse mail correspondant"
      operationId: "sendCode"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "email"
          required: true
          type: "string"
      responses:
        200:
          description: "Code envoyé à l'email"
          schema:
            type: "string"
    post:
      tags:
        - "user"
      summary: "Vérification du code"
      description: "Vérifie le code qui a été envoyé par mail"
      operationId: "checkCode"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "codeCheck"
          required: true
          schema:
            $ref: "#/definitions/CodeCheck"
      responses:
        200:
          description: "Feedback sur la vérification du code"
          schema:
            type: "string"
  /auth/login:
    post:
      tags:
        - "auth"
      summary: "Se connecter à la plateforme"
      description: "Se connecter à la plateforme en fournissant les identifiants"
      operationId: "login"
      produces:
        - "application/json"
      parameters:
        - name: "credentials"
          in: "body"
          description: "Les identifiants de l'utilisateur"
          required: true
          schema:
            $ref: "#/definitions/Credentials"
      responses:
        200:
          description: "token"
          schema:
            type: "string"
        400:
          description: "email ou mot de passe invalide"
          schema:
            type: "string"
  /auth/logout:
    post:
      tags:
        - "auth"
      summary: "Se déconnecter de la plateforme"
      description: "Se déconnecter de la plateforme"
      operationId: "logout"
      produces:
        - "application/json"
      parameters: []
      responses:
        200:
          description: "Opération réussie"
          schema:
            type: "string"
definitions:
  UserDTO:
    type: "object"
    properties:
      email:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      password:
        type: "string"
      role:
        type: "string"
      blocked:
        type: "boolean"
        default: false
  PagedResponse:
    type: "object"
    properties:
      content:
        type: "array"
        items:
          type: "object"
      pageNumber:
        type: "integer"
        default: 1
      pageSize:
        type: "integer"
        default: 10
      totalPages:
        type: "integer"
      totalElements:
        type: "integer"
  Credentials:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
  CodeCheck:
    type: "object"
    properties:
      email:
        type: "string"
      code:
        type: "string"
  UserId:
    type: "object"
    properties:
      userId:
        type: "string"
  ResetPassword:
    type: "object"
    properties:
      token:
        type: "string"
      newPassword:
        type: "string"
  ChangePassword:
    type: "object"
    properties:
      newPassword:
        type: "string"
      oldPassword:
        type: "string"