version: '3'
services:
  traefik:
    image: 'traefik:v2.0.0-rc3'
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '90:80'
      - '8090:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
  first-backend-db:
    image: 'mysql:latest'
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - 'first-backend-db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=superpwd
      - MYSQL_USER=dorianekaffo
      - MYSQL_PASSWORD=simplepwd
      - MYSQL_DATABASE=first_backend
    ports:
      - '3100:3306'
  first-backend:
    image: amt2019/first-backend
    expose:
      - 8080
    ports:
      - '8070:8080'
    labels:
      - traefik.enable=true
      - traefik.http.routers.first_backend.rule=PathPrefix(`/users`) || PathPrefix(`/auth`)
    volumes:
      - 'first-backend:/tmp/fichiers'
    depends_on:
      - first-backend-db
    links:
      - 'first-backend-db:first-backend-db'
  second-backend-db:
    image: 'mysql:latest'
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - 'second-backend-db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=superpwd
      - MYSQL_USER=dorianekaffo
      - MYSQL_PASSWORD=simplepwd
      - MYSQL_DATABASE=second_backend
    ports:
      - '3200:3306'
  second-backend:
    image: amt2019/second-backend
    expose:
      - 8080
    ports:
      - '8100:8080'
    labels:
      - traefik.enable=true
      - traefik.http.routers.second_backend.rule=PathPrefix(`/students`) || PathPrefix(`/enrollments`) || PathPrefix(`/courses`)
    volumes:
      - 'second-backend:/tmp/fichiers'
    depends_on:
      - second-backend-db
    links:
      - 'second-backend-db:second-backend-db'
volumes:
  first-backend:
  first-backend-db:
  second-backend:
  second-backend-db:
