swagger: "2.0"
info:
  description: "Ce serveur a été construit dans le cadre du deuxième projet de l'AMT 2019. Ceci regroupe les APIs de la première partie du projet."
  version: "1.0.0"
  title: "AMT 2019 - Project Two API"
  termsOfService: ""
host: "localhost:8080"
basePath: "/"
tags:
- name: "user"
  description: "Les opérations sur les utilisateurs"
- name: "auth"
  description: "Les opérations pour l'authentification des utilisateur"
schemes:
- "https"
- "http"
paths:
  /users:
    post:
      tags:
      - "user"
      summary: "Créer un utilisateur"
      description: "Crée un nouvel utilisateur"
      operationId: "createUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Utilisateur à créer"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "Opération réussie"
    get:
      tags:
      - "user"
      summary: "Liste de tous les utilisateurs"
      description: "Liste complète de tous les utilisateurs"
      operationId: "getUsers"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        default:
          description: "Tous les utilisateurs"
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
  /login:
    get:
      tags:
      - "auth"
      summary: "Se connecter à la plateforme"
      description: "Se connecter à la plateforme en fournissant les identifiants"
      operationId: "loginUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "credentials"
        in: "body"
        description: "Les identifiants de l'utilisateur"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
            password:
              type: "string"
      responses:
        200:
          description: "Connexion effectuée avec token envoyée"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "email ou mot de passe invalide"
  /logout:
    get:
      tags:
      - "auth"
      summary: "Se déconnecter de la plateforme"
      description: "Se déconnecter de la plateforme"
      operationId: "logoutUser"
      produces:
      - "application/json"
      parameters: []
      responses:
        default:
          description: "Opération réussie"
  /user/block/{email}:
    put:
      tags:
      - "user"
      summary: "Bloque l'utilisateur ayant l'email correspondant"
      description: "Bloque l'utilisateur ayant l'`email` correspondant"
      operationId: "blockUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: path
        name: email
        type: "string"
        required: true
      responses:
        default:
          description: "Operation"
    delete:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "unblockUSer"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: path
        name: email
        type: "string"
        required: true
      responses:
        default:
          description: "Opération réussie"
  /user/changePassword:
    post:
      tags:
      - "user"
      summary: "Change le mot de passe de l'utilisateur"
      description: "Change le mot de passe de l'utilisateur"
      operationId: "changePassword"
      produces:
      - "application/json"
      parameters:
        - in: "body"
          name: "changePassword"
          required: true
          schema:
            type: "object"
            properties:
              oldPassword:
                type: string
              newPassword:
                type: string
      responses:
        default:
          description: "Opération réussie"
  /user/resetPassword:
    get:
      tags:
      - "user"
      summary: "Ouvre la page pour le changement de mot de passe"
      description: "Ouvre la page pour le changement du mot de passe"
      operationId: "resetPasswordPage"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "token"
        required: true
        type: "string"
      responses:
        default:
          description: "Mot de passe changé"
    post:
      tags:
      - "user"
      summary: "Change le mot de passe de l'utilisateur"
      description: ""
      operationId: "resetPassword"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            token:
              type: string
            newPassword:
              type: string
      responses:
        default:
          description: "Mot de passe changé"
  /user/{email}:
    get:
      tags:
      - "user"
      summary: "Récupère un utilisateur avec l'email correspondant"
      description: "Récupère un utilisateur avec l'`email` correspondant"
      operationId: "getUserByName"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "email"
        in: "path"
        description: "Email de l'utilisateur à récupérer"
        required: true
        type: "string"
      responses:
        200:
          description: "Opération réussie"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Email invalide"
        404:
          description: "Utilisateur non trouvée"
    put:
      tags:
      - "user"
      summary: "Mettre à jour un utilisateur"
      description: "Mets à jour l'utilisateur avec l'`email` correspondant. Ne peut qu'être fait par un utilisateur connecté"
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "path"
        description: "email de l'utilisateur à mettre à jour"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Utilisateur à mettre à jour"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        400:
          description: "Email invalide"
        404:
          description: "Utilisateur non retrouvé"
    delete:
      tags:
      - "user"
      summary: "Supprime un utilisateur"
      description: "Supprime un utilisateur avec `email` comme adresse email. Cette action ne peut qu'être effectué par l'administrateur"
      operationId: "deleteUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "email"
        in: "path"
        description: "Email de l'utilisateur à supprimer"
        required: true
        type: "string"
      responses:
        400:
          description: "Email invalide"
        404:
          description: "Utilisateur non trouvée"
definitions:
  User:
    type: "object"
    properties:
      email:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      password:
        type: "string"
      blocked:
        type: "boolean"
        default: false
