version: '3.7'
services:
    traefik:
        image: 'traefik:v2.0.0-rc3'
        container_name: traefik
        command:
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--providers.docker.exposedbydefault=false'
            - '--entrypoints.web.address=:80'
        ports:
            - '90:80'
            - '8090:8080'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
    server_one_db:
        image: 'mysql:latest'
        restart: always
        command: '--default-authentication-plugin=mysql_native_password'
        volumes:
            - '/home/new_docker:/var/lib/mysql'
        environment:
            - MYSQL_ROOT=dorianekaffo
            - MYSQL_ROOT_PASSWORD=simplepwd
            - MYSQL_DATABASE=firstapi
        ports:
            - '3100:3306'
    firstapi:
        build: ../../first-api
        expose:
            - 8080
        labels:
            - traefik.enable=true
            - traefik.http.routers.firstapi.rule=PathPrefix(`/users/`)
        volumes:
            - '/home/new_docker/files:/tmp/fichiers'
        depends_on:
            - server_one_db
        links:
            - 'server_one_db:server_one_db'

    server_two_db:
        image: 'mysql:latest'
        restart: always
        command: '--default-authentication-plugin=mysql_native_password'
        volumes:
            - '/home/new_docker:/var/lib/mysql'
        environment:
            - MYSQL_ROOT=dorianekaffo
            - MYSQL_ROOT_PASSWORD=simplepwd
            - MYSQL_DATABASE=firstapi
        ports:
            - '3100:3306'
    employees:
        build: ../../employees
        expose:
            - 8080
        labels:
            - traefik.enable=true
            - traefik.http.routers.firstapi.rule=PathPrefix(`/employees/`)
        volumes:
            - '/home/new_docker/files:/tmp/fichiers'
        depends_on:
            - server_two_db
        links:
            - 'server_two_db:server_two_db'

